<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Doc\InvalidParameterHandler::class => App\Doc\InvalidParameterHandlerFactory::class,
            App\Doc\MethodNotAllowedHandler::class => App\Doc\MethodNotAllowedHandlerFactory::class,
            App\Doc\OutOfBoundsHandler::class => App\Doc\OutOfBoundsHandlerFactory::class,
            App\Doc\ResourceNotFoundHandler::class => App\Doc\ResourceNotFoundHandlerFactory::class,
            App\Doc\RuntimeErrorHandler::class => App\Doc\RuntimeErrorHandlerFactory::class,
        ],
    ],
];
